### ISSUE TITLE
Stuck in "Waiting for a notification" and no comment after lot of test

### ISSUE THREAD

**Issue by gt0203** [Eliasyoussef47/InstaAutoComment#3]
hello,

Thanks for sharing!

I have a problem, when I run node index.js it puts me :
Tracking: myuser (I put my nickname it's just an example here)
Waiting for a notification 

and nothing happens, I've tested with several accounts and it's the same.

Thank you in advance.

**Comment by Eliasyoussef47** [comment]
Hi,

Thanks for using this.

Make sure you have turned on post notification for the account you want to auto comment on.


The Configuration part of the Readme is outdated, I'm going to fix it, you need to put the usernames of the users you want to auto comment on in the .env file not the pk.

So let's say you want to place a comment every time Eminem posts something, then you would add eminem to TRACKED_USERS_USERNAMES in your .env file open the same account you're going to use with this program on your phone and go to Eminem's account and turn on post notification and then start this program.

To make sure this program works, I would advise you to have two Instagram accounts so you can post from one account and use this program to auto comment from the other account.

**Comment by gt0203** [comment]
Amazing, Thank you !

It works perfectly ! Thanks to you for the quick answer and thanks for sharing this :)
